import { CATALOGS } from './catalogs'

export const DEFAULT_DATA = {
	[CATALOGS.chairs.key]: [
		{
			id: '1',
			name: 'Эклипс',
			price: 5000,
			type: CATALOGS.chairs.value,
			image: '/images/User/Catalogs/Chairs/eclips.png',
		},
		{
			id: '2',
			name: 'Мини-терра',
			price: 8000,
			type: CATALOGS.chairs.value,
			image: '/images/User/Catalogs/Chairs/mini-terra.png',
		},
		{
			id: '3',
			name: 'Терра',
			price: 6500,
			type: CATALOGS.chairs.value,
			image: '/images/User/Catalogs/Chairs/terra.png',
		},
	],
	[CATALOGS.tables.key]: [
		{
			id: '1',
			name: 'Лотос',
			price: 22000,
			type: CATALOGS.tables.value,
			image: '/images/User/Catalogs/Tables/lotos.png',
		},
		{
			id: '2',
			name: 'Гравити',
			price: 48000,
			type: CATALOGS.tables.value,
			image: '/images/User/Catalogs/Tables/gravity.png',
		},
		{
			id: '3',
			name: 'Techno',
			price: 34500,
			type: CATALOGS.tables.value,
			image: '/images/User/Catalogs/Tables/techno.png',
		},
	],
	[CATALOGS.storageSystems.key]: [
		{
			id: '1',
			name: 'Квадро',
			price: 35000,
			type: CATALOGS.storageSystems.value,
			image: '/images/User/Catalogs/StorageSystem/quadro.png',
		},
		{
			id: '2',
			name: 'Эдем',
			price: 28000,
			type: CATALOGS.storageSystems.value,
			image: '/images/User/Catalogs/StorageSystem/edem.png',
		},
		{
			id: '3',
			name: 'Ларго',
			price: 46500,
			type: CATALOGS.storageSystems.value,
			image: '/images/User/Catalogs/StorageSystem/largo.png',
		},
	],
	[CATALOGS.upFurniture.key]: [
		{
			id: '1',
			name: 'Эклипс',
			price: 25000,
			type: CATALOGS.upFurniture.value,
			image: '/images/User/Catalogs/UpFurniture/eclips.png',
		},
		{
			id: '2',
			name: 'Небла',
			price: 38000,
			type: CATALOGS.upFurniture.value,
			image: '/images/User/Catalogs/UpFurniture/nebla.webp',
		},
		{
			id: '3',
			name: 'Терра',
			price: 62200,
			type: CATALOGS.upFurniture.value,
			image: '/images/User/Catalogs/UpFurniture/terra.png',
		},
	],
	[CATALOGS.partitions.key]: [
		{
			id: '1',
			name: 'Люмен',
			price: 8000,
			type: CATALOGS.partitions.value,
			image: '/images/User/Catalogs/Partitions/lumen.webp',
		},
		{
			id: '2',
			name: 'Бриз',
			price: 5000,
			type: CATALOGS.partitions.value,
			image: '/images/User/Catalogs/Partitions/briz.webp',
		},
		{
			id: '3',
			name: 'Фьюжн',
			price: 7500,
			type: CATALOGS.partitions.value,
			image: '/images/User/Catalogs/Partitions/fushn.png',
		},
	],
	[CATALOGS.reception.key]: [
		{
			id: '1',
			name: 'Эпицентр',
			price: 65000,
			type: CATALOGS.reception.value,
			image: '/images/User/Catalogs/Reception/epicenter.webp',
		},
		{
			id: '2',
			name: 'Грация',
			price: 68000,
			type: CATALOGS.reception.value,
			image: '/images/User/Catalogs/Reception/gracia.png',
		},
		{
			id: '3',
			name: 'Нексус',
			price: 76500,
			type: CATALOGS.reception.value,
			image: '/images/User/Catalogs/Reception/nexus.png',
		},
	],
	[CATALOGS.accessories.key]: [
		{
			id: '1',
			name: 'Ручка для двери',
			price: 500,
			type: CATALOGS.accessories.value,
			image: '/images/User/Catalogs/Accessories/handmark.png',
		},
		{
			id: '2',
			name: 'Петля двери',
			price: 200,
			type: CATALOGS.accessories.value,
			image: '/images/User/Catalogs/Accessories/loop.webp',
		},
		{
			id: '3',
			name: 'Раскладной механизм',
			price: 2400,
			type: CATALOGS.accessories.value,
			image: '/images/User/Catalogs/Accessories/folding-mechanism.webp',
		},
	],
}
