export const BURGER_MENU_SLUG = 'BURGER_MENU_SLUG'
export const SIDEBAR_SLUG = 'SIDEBAR_SLUG'
export const ADD_CATALOG_ITEM_SLUG = 'ADD_CATALOG_ITEM_SLUG'
export const EDIT_CATALOG_ITEM_SLUG = 'EDIT_CATALOG_ITEM_SLUG'
export const HOME_STAGES_WORK_CONSULTATION_SLUG =
	'HOME_STAGES_WORK_CONSULTATION_SLUG'
